spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${YJY.mysql.host}:3306/user_management
    username: root
    password: ${YJY.mysql.password}
  redis:
    port: 6379
    database: 0
    host: localhost
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #      路径匹配策略
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
knife4j:
  enable: true
#  生产环境下不可以访问
#  production: true

server:
  port: 8081
  servlet:
    context-path: /api
